VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "WorksheetChange"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
'**********************************************************************************************
' 図面番号　                ：FSP01080800003
' 名称　                    ：プロセスツリー自動作成ツール機能安全課編図面
' ソフトウェア管理番号ＩＤ　：FSS0101032
' ソフトウェア名　          ：プロセスツリー自動作成ツール機能安全課編
' モジュール名　            ：Worksheet_Change
' 機能概要　　　            ：プロジェクト管理時、プロセスツリーの作成と運用管理を自動化する。
'
' 改訂履歴　　　            ：2018/08/30 新規 T.Takayasu
' 　　　　　　　            　2018/09/21 修正 T.Takayasu 　diff（差分補助機能追加）
'                             2018/10/11全削除 T.takayasu
'
' Copyright(C) 2018 Sanken Electric Co., Ltd. All Rights Reserved.
'**********************************************************************************************


